// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB;
using LinqToDB.Data;

#pragma warning disable 1573, 1591
#nullable enable

namespace DataModels

// generiert mit: dotnet linq2db scaffold -p SQLite -c "Data Source=Wordle.db" -o . --namespace DataModels

{
    public partial class WordleDB : DataConnection
	{
		public WordleDB()
		{
			InitDataContext();
		}

		public WordleDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		public WordleDB(DataOptions<WordleDB> options)
			: base(options.Options)
		{
			InitDataContext();
		}

		partial void InitDataContext();

		public ITable<Woerter> Woerters => this.GetTable<Woerter>();
	}
}
