//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace WaldwunderDB
{
	/// <summary>
	/// Database       : Waldwunder
	/// Data Source    : Waldwunder
	/// Server Version : 3.50.4
	/// </summary>
	public partial class WaldwunderDB : LinqToDB.Data.DataConnection
	{
		#region Tables

		public ITable<Bilder>     Bilders     { get { return this.GetTable<Bilder>(); } }
		public ITable<Waldwunder> Waldwunders { get { return this.GetTable<Waldwunder>(); } }

		#endregion

		#region .ctor

		public WaldwunderDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public WaldwunderDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public WaldwunderDB(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public WaldwunderDB(DataOptions<WaldwunderDB> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();

		#endregion
	}

	[Table(Schema="main", Name="Bilder")]
	public partial class Bilder
	{
		[Column("id"),     PrimaryKey, Identity, Nullable] public long?    Id     { get; set; } // INTEGER
		[Column("name"),                         Nullable] public string   Name   { get; set; } // TEXT
		[Column("wonder"),                       Nullable] public decimal? Wonder { get; set; } // NUMERIC

        #region Associations

        /// <summary>
        /// FK_Bilder_0 (main.Waldwunder)
        /// </summary>
        [Association(ThisKey = nameof(Wonder), OtherKey = nameof(Waldwunder.Id), CanBeNull = true)]
        public Waldwunder Waldwunder { get; set; }

        #endregion
    }

	[Table(Schema="main", Name="Waldwunder")]
	public partial class Waldwunder
	{
		[Column("id"),          PrimaryKey, Identity, Nullable] public long?    Id          { get; set; } // INTEGER
		[Column("name"),                              Nullable] public string   Name        { get; set; } // TEXT
		[Column("description"),                       Nullable] public string   Description { get; set; } // TEXT
		[Column("province"),                          Nullable] public string   Province    { get; set; } // TEXT
		[Column("latitude"),                          Nullable] public decimal? Latitude    { get; set; } // NUMERIC
		[Column("longitude"),                         Nullable] public decimal? Longitude   { get; set; } // NUMERIC
		[Column("type"),                              Nullable] public string   Type        { get; set; } // TEXT
		[Column("votes"),                             Nullable] public decimal? Votes       { get; set; } // NUMERIC

        #region Associations

        /// <summary>
        /// FK_Bilder_0_BackReference (main.Bilder)
        /// </summary>
        [Association(ThisKey = nameof(Id), OtherKey = nameof(Bilder.Wonder), CanBeNull = true)]
        public IEnumerable<Bilder> Bilders { get; set; }

        #endregion
    }

	public static partial class TableExtensions
	{
		public static Bilder Find(this ITable<Bilder> table, long? Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}

		public static Waldwunder Find(this ITable<Waldwunder> table, long? Id)
		{
			return table.FirstOrDefault(t =>
				t.Id == Id);
		}
	}
}
