<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>WPF_Server</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="linq2db" Version="6.2.1" />
    <PackageReference Include="linq2db.SQLite" Version="6.2.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.5" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.11" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetworkLibrary\NetworkLibrary.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="NetworkLibrary_2026">
      <HintPath>..\NetworkLibrary_2026\obj\Debug\net8.0\NetworkLibrary_2026.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="Model\Chat.db">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Model\ChatModel.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>ChatModel.generated.cs</LastGenOutput>
    </None>
    <None Update="Model\sqlite3.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Model\ChatModel.generated.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ChatModel.tt</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
