





//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;

using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : Babynames
	/// Data Source    : Babynames
	/// Server Version : 3.40.1
	/// </summary>
	public partial class BabynamesDB : LinqToDB.Data.DataConnection
	{
		#region Tables

		public ITable<Babyname> Babynames { get { return this.GetTable<Babyname>(); } }

		#endregion

		#region .ctor

		public BabynamesDB()
		{
			InitDataContext();
			InitMappingSchema();
		}

		public BabynamesDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public BabynamesDB(DataOptions options)
			: base(options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		public BabynamesDB(DataOptions<BabynamesDB> options)
			: base(options.Options)
		{
			InitDataContext();
			InitMappingSchema();
		}

		partial void InitDataContext  ();
		partial void InitMappingSchema();

		#endregion
	}

	[Table(Schema="main", Name="Babynames")]
	public partial class Babyname
	{
		[Column, NotNull] public string Name  { get; set; } // TEXT
		[Column, NotNull] public long   Year  { get; set; } // INTEGER
		[Column, NotNull] public string Sex   { get; set; } // TEXT
		[Column, NotNull] public long   Count { get; set; } // INTEGER
	}
}
